/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    Phosphate_Backbone: THREE.Mesh;
    ["Adenine_(A)"]: THREE.Mesh;
    ["Thymine_(T)"]: THREE.Mesh;
    ["Adenine_(A)001"]: THREE.Mesh;
    ["Thymine_(T)001"]: THREE.Mesh;
    ["Adenine_(A)002"]: THREE.Mesh;
    ["Thymine_(T)002"]: THREE.Mesh;
    ["Adenine_(A)003"]: THREE.Mesh;
    ["Thymine_(T)003"]: THREE.Mesh;
    ["Adenine_(A)004"]: THREE.Mesh;
    ["Thymine_(T)004"]: THREE.Mesh;
    ["Adenine_(A)005"]: THREE.Mesh;
    ["Thymine_(T)005"]: THREE.Mesh;
    ["Cytosine_(C)"]: THREE.Mesh;
    ["Guanine_(G)"]: THREE.Mesh;
    ["Cytosine_(C)001"]: THREE.Mesh;
    ["Guanine_(G)001"]: THREE.Mesh;
    ["Cytosine_(C)002"]: THREE.Mesh;
    ["Guanine_(G)002"]: THREE.Mesh;
    ["Cytosine_(C)003"]: THREE.Mesh;
    ["Guanine_(G)003"]: THREE.Mesh;
    ["Cytosine_(C)004"]: THREE.Mesh;
    ["Guanine_(G)004"]: THREE.Mesh;
    ["Cytosine_(C)005"]: THREE.Mesh;
    ["Guanine_(G)005"]: THREE.Mesh;
  };
  materials: {
    White: THREE.MeshStandardMaterial;
    Red: THREE.MeshStandardMaterial;
    Blue: THREE.MeshStandardMaterial;
    Yellow: THREE.MeshStandardMaterial;
    Green: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF("/dna-5.gltf") as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials.White}
        geometry={nodes.Phosphate_Backbone.geometry}
        scale={[0.36204421520233154, 1, 0.36204421520233154]}
      />
      <mesh
        material={materials.Red}
        geometry={nodes["Adenine_(A)"].geometry}
        position={[-0.23, 3.72, -0.22]}
        rotation={[0, -0.89, -Math.PI / 2]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        material={materials.Blue}
        geometry={nodes["Thymine_(T)"].geometry}
        position={[0.12, 3.72, 0.21]}
        rotation={[0, -0.89, -Math.PI / 2]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        material={materials.Red}
        geometry={nodes["Adenine_(A)001"].geometry}
        position={[-0.23, 3.12, -0.18]}
        rotation={[0, -0.42, -Math.PI / 2]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        material={materials.Blue}
        geometry={nodes["Thymine_(T)001"].geometry}
        position={[0.26, 3.12, 0.04]}
        rotation={[0, -0.42, -Math.PI / 2]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        material={materials.Red}
        geometry={nodes["Adenine_(A)002"].geometry}
        position={[0.07, 2.92, 0.27]}
        rotation={[-Math.PI, 1.34, Math.PI / 2]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        material={materials.Blue}
        geometry={nodes["Thymine_(T)002"].geometry}
        position={[-0.05, 2.92, -0.26]}
        rotation={[-Math.PI, 1.34, Math.PI / 2]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        material={materials.Red}
        geometry={nodes["Adenine_(A)003"].geometry}
        position={[-0.04, 2.12, 0.27]}
        rotation={[0, 1.38, -Math.PI / 2]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        material={materials.Blue}
        geometry={nodes["Thymine_(T)003"].geometry}
        position={[0.07, 2.12, -0.26]}
        rotation={[0, 1.38, -Math.PI / 2]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        material={materials.Red}
        geometry={nodes["Adenine_(A)004"].geometry}
        position={[0.2, 1.92, -0.22]}
        rotation={[Math.PI, -0.49, Math.PI / 2]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        material={materials.Blue}
        geometry={nodes["Thymine_(T)004"].geometry}
        position={[-0.27, 1.92, 0.03]}
        rotation={[Math.PI, -0.49, Math.PI / 2]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        material={materials.Red}
        geometry={nodes["Adenine_(A)005"].geometry}
        position={[-0.02, 1.52, -0.29]}
        rotation={[0, -1.29, -Math.PI / 2]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        material={materials.Blue}
        geometry={nodes["Thymine_(T)005"].geometry}
        position={[0.13, 1.52, 0.23]}
        rotation={[0, -1.29, -Math.PI / 2]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        material={materials.Yellow}
        geometry={nodes["Cytosine_(C)"].geometry}
        position={[-0.08, 3.52, 0.2]}
        rotation={[Math.PI, -1.36, Math.PI / 2]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        material={materials.Green}
        geometry={nodes["Guanine_(G)"].geometry}
        position={[0.03, 3.52, -0.32]}
        rotation={[Math.PI, -1.36, Math.PI / 2]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        material={materials.Yellow}
        geometry={nodes["Cytosine_(C)001"].geometry}
        position={[-0.23, 3.32, 0.07]}
        rotation={[-Math.PI, -0.47, Math.PI / 2]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        material={materials.Green}
        geometry={nodes["Guanine_(G)001"].geometry}
        position={[0.25, 3.32, -0.17]}
        rotation={[Math.PI, -0.47, Math.PI / 2]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        material={materials.Yellow}
        geometry={nodes["Cytosine_(C)002"].geometry}
        position={[0.21, 2.72, -0.17]}
        rotation={[0, 0.91, -Math.PI / 2]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        material={materials.Green}
        geometry={nodes["Guanine_(G)002"].geometry}
        position={[-0.12, 2.72, 0.26]}
        rotation={[0, 0.91, -Math.PI / 2]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        material={materials.Yellow}
        geometry={nodes["Cytosine_(C)003"].geometry}
        position={[-0.27, 2.52, 0.05]}
        rotation={[Math.PI, -0.02, Math.PI / 2]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        material={materials.Green}
        geometry={nodes["Guanine_(G)003"].geometry}
        position={[0.27, 2.52, 0.04]}
        rotation={[Math.PI, -0.02, Math.PI / 2]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        material={materials.Yellow}
        geometry={nodes["Cytosine_(C)004"].geometry}
        position={[-0.18, 2.32, -0.16]}
        rotation={[-Math.PI, 0.87, Math.PI / 2]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        material={materials.Green}
        geometry={nodes["Guanine_(G)004"].geometry}
        position={[0.17, 2.32, 0.25]}
        rotation={[-Math.PI, 0.87, Math.PI / 2]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        material={materials.Yellow}
        geometry={nodes["Cytosine_(C)005"].geometry}
        position={[0.3, 1.72, 0.03]}
        rotation={[0, -0.41, -Math.PI / 2]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        material={materials.Green}
        geometry={nodes["Guanine_(G)005"].geometry}
        position={[-0.2, 1.72, -0.19]}
        rotation={[0, -0.41, -Math.PI / 2]}
        scale={[0.05, 0.25, 0.05]}
      />
    </group>
  );
}

useGLTF.preload("/dna-5.gltf");
