/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/materials--colour.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={materials.Red} geometry={nodes.Cube.geometry} />
      <mesh
        material={materials.Yellow}
        geometry={nodes.Sphere.geometry}
        position={[1.78, 0.79, -6.3]}
      />
      <mesh
        material={materials.Blue}
        geometry={nodes.Cube001.geometry}
        position={[-1.78, 2.84, 2.98]}
      />
      <mesh
        material={materials.Yellow}
        geometry={nodes.Sphere001.geometry}
        position={[0, 3.63, -3.32]}
      />
    </group>
  );
}

useGLTF.preload("materials--colour.gltf");
