/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 hemoglobin-pdb-spacefill.gltf --types 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh;
    mesh_1: THREE.Mesh;
    mesh_2: THREE.Mesh;
    mesh_3: THREE.Mesh;
    mesh_4: THREE.Mesh;
    mesh_5: THREE.Mesh;
    mesh_6: THREE.Mesh;
    mesh_7: THREE.Mesh;
    mesh_8: THREE.Mesh;
    mesh_9: THREE.Mesh;
    mesh_10: THREE.Mesh;
    mesh_11: THREE.Mesh;
    mesh_12: THREE.Mesh;
    mesh_13: THREE.Mesh;
    mesh_14: THREE.Mesh;
    mesh_15: THREE.Mesh;
    mesh_16: THREE.Mesh;
    mesh_17: THREE.Mesh;
    mesh_18: THREE.Mesh;
    mesh_19: THREE.Mesh;
    mesh_20: THREE.Mesh;
    mesh_21: THREE.Mesh;
    mesh_22: THREE.Mesh;
    mesh_23: THREE.Mesh;
    mesh_24: THREE.Mesh;
    mesh_25: THREE.Mesh;
    mesh_26: THREE.Mesh;
  };
  materials: {};
  animations: GLTFAction[];
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/hemoglobin-pdb-spacefill.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.mesh_0.geometry}
        material={nodes.mesh_0.material}
        position={[-14.7, -0.968, -13.673]}
        opacity={0.5}
      />
      <mesh
        geometry={nodes.mesh_1.geometry}
        material={nodes.mesh_1.material}
        position={[-14.7, -0.968, -13.673]}
      />
      <mesh
        geometry={nodes.mesh_2.geometry}
        material={nodes.mesh_2.material}
        position={[-14.7, -0.968, -13.673]}
      />
      <mesh
        geometry={nodes.mesh_3.geometry}
        material={nodes.mesh_3.material}
        position={[-14.7, -0.968, -13.673]}
      />
      <mesh
        geometry={nodes.mesh_4.geometry}
        material={nodes.mesh_4.material}
        position={[-14.7, -0.968, -13.673]}
      />
      <mesh
        geometry={nodes.mesh_5.geometry}
        material={nodes.mesh_5.material}
        position={[-14.7, -0.968, -13.673]}
      />
      <mesh
        geometry={nodes.mesh_6.geometry}
        material={nodes.mesh_6.material}
        position={[-14.7, -0.968, -13.673]}
      />
      <mesh
        geometry={nodes.mesh_7.geometry}
        material={nodes.mesh_7.material}
        position={[-14.7, -0.968, -13.673]}
      />
      <mesh
        geometry={nodes.mesh_8.geometry}
        material={nodes.mesh_8.material}
        position={[-14.7, -0.968, -13.673]}
      />
      <mesh
        geometry={nodes.mesh_9.geometry}
        material={nodes.mesh_9.material}
        position={[-14.7, -0.968, -13.673]}
      />
      <mesh
        geometry={nodes.mesh_10.geometry}
        material={nodes.mesh_10.material}
        position={[-14.7, -0.968, -13.673]}
      />
      <mesh
        geometry={nodes.mesh_11.geometry}
        material={nodes.mesh_11.material}
        position={[-14.7, -0.968, -13.673]}
      />
      <mesh
        geometry={nodes.mesh_12.geometry}
        material={nodes.mesh_12.material}
        position={[-14.7, -0.968, -13.673]}
      />
      <mesh
        geometry={nodes.mesh_13.geometry}
        material={nodes.mesh_13.material}
        position={[-14.7, -0.968, -13.673]}
      />
      <mesh
        geometry={nodes.mesh_14.geometry}
        material={nodes.mesh_14.material}
        position={[-14.7, -0.968, -13.673]}
      />
      <mesh
        geometry={nodes.mesh_15.geometry}
        material={nodes.mesh_15.material}
        position={[-14.7, -0.968, -13.673]}
      />
      <mesh
        geometry={nodes.mesh_16.geometry}
        material={nodes.mesh_16.material}
        position={[-14.7, -0.968, -13.673]}
      />
      <mesh
        geometry={nodes.mesh_17.geometry}
        material={nodes.mesh_17.material}
        position={[-14.7, -0.968, -13.673]}
      />
      <mesh
        geometry={nodes.mesh_18.geometry}
        material={nodes.mesh_18.material}
        position={[-14.7, -0.968, -13.673]}
      />
      <mesh
        geometry={nodes.mesh_19.geometry}
        material={nodes.mesh_19.material}
        position={[-14.7, -0.968, -13.673]}
      />
      <mesh
        geometry={nodes.mesh_20.geometry}
        material={nodes.mesh_20.material}
        position={[-14.7, -0.968, -13.673]}
      />
      <mesh
        geometry={nodes.mesh_21.geometry}
        material={nodes.mesh_21.material}
        position={[-14.7, -0.968, -13.673]}
      />
      <mesh
        geometry={nodes.mesh_22.geometry}
        material={nodes.mesh_22.material}
        position={[-14.7, -0.968, -13.673]}
      />
      <mesh
        geometry={nodes.mesh_23.geometry}
        material={nodes.mesh_23.material}
        position={[-14.7, -0.968, -13.673]}
      />
      <mesh
        geometry={nodes.mesh_24.geometry}
        material={nodes.mesh_24.material}
        position={[-14.7, -0.968, -13.673]}
      />
      <mesh
        geometry={nodes.mesh_25.geometry}
        material={nodes.mesh_25.material}
        position={[-14.7, -0.968, -13.673]}
      />
      <mesh
        geometry={nodes.mesh_26.geometry}
        material={nodes.mesh_26.material}
        position={[-14.7, -0.968, -13.673]}
      />
    </group>
  );
}

useGLTF.preload("/hemoglobin-pdb-spacefill.gltf");
